### ISSUE TITLE
Disabling outline doesn't work

### ISSUE THREAD

**Issue by VildMedPap** [AnKing-VIP/The-KING-of-Button-Add-ons#17]
Setting `outline` to `no` doesn't work:

<img width="1092" alt="CleanShot 2022-02-20 at 14 31 56" src="https://user-images.githubusercontent.com/23236622/154845080-6bf9472d-3eee-41e9-a28f-38d35105e3ff.png">

**My config**
```json
{
    "AgainColor": "red",
    "EasyColor": "#61a8ff",
    "GoodColor": "#30c257",
    "HardColor": "orange",
    "Nightmode_AgainColor": "#ff6961",
    "Nightmode_EasyColor": "#61a8ff",
    "Nightmode_GoodColor": "#61ffb8",
    "Nightmode_HardColor": "#ffb861",
    "answer button width": "Normal",
    "border radius": "10",
    "button color": "default",
    "button font size": "M",
    "button height": "M",
    "button width": "M",
    "confirmation": false,
    "confirmation time": 100,
    "confirmation x-offset": 0,
    "confirmation y-offset": 0,
    "outline": "no",
    "style main screen buttons": true
}
```

**Did I restart Anki after updating config?**
Yes

**Suggested solution**
I'm no CSS hero, but maybe the following would work?
```css
:focus {
    outline: 0;
}
```

**Version**
Anki version ⁨2.1.49 (dc80804a)⁩

**Comment by abdnh** [comment]
The outline was removed from Anki in 2.1.55. @AnKingMed maybe we should remove the option or stop supporting it?

**Comment by AnKingMed** [comment]
yeah that sounds reasonble.
