### ISSUE TITLE
Size of button is too large

### ISSUE THREAD

**Issue by AbdelrahmanMahmoudMD** [AnKing-VIP/The-KING-of-Button-Add-ons#20]
**Anki version**
Version ⁨2.1.55 (01caec2a)⁩
Python 3.9.15 Qt 6.4.0 PyQt 6.4.0
**OS**
Windows 10

**Problem**

(1) The border radius doesn't fit the new rounded corner of anki 2.1.55, and I don't know what is the radius of the new UI to match it

(2) The size of buttons are too large even if the size is set to small *S*, however I believe this has to be something related to the resolution, my screen resolution is 1366 x 768

Thanks for your great work

![image](https://user-images.githubusercontent.com/79529298/210353414-498f2d98-874a-4cb4-a96b-2f2b3f92c6f4.png)

![image](https://user-images.githubusercontent.com/79529298/210353294-d1ea40b8-a956-4b13-b87e-1d10bb635dc6.png)

**Comment by tndk323** [comment]
I have the same issue where the border is too visible and thick. The size of the buttons for "S" is still too large for me as well. Thank you so much!

Version ⁨2.1.64 (581f82c5)⁩
Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Windows 11

**Comment by AnKingMed** [comment]
@abdnh this is lower priority, but we can look into this whenever you have time

**Comment by kiler129** [comment]
This also cuts-off buttons AnkiHub buttons when the window size isn't wide enough. By default, it will make them smaller, but with this addon it seems like button widths are set to static size and no longer respect fluidity.

![image](https://github.com/AnKing-VIP/The-KING-of-Button-Add-ons/assets/1227834/5632f7f6-d14c-4345-b1d0-4194d8b18869)
![image](https://github.com/AnKing-VIP/The-KING-of-Button-Add-ons/assets/1227834/a6b60b0b-0f4f-40d6-9cea-fd23d225e2fb)
![image](https://github.com/AnKing-VIP/The-KING-of-Button-Add-ons/assets/1227834/0d7bf1f2-c42c-4275-8d42-10088b6fff8b)

**Comment by abdnh** [comment]
Should be fixed now.
