### ISSUE TITLE
Night mode toggle issues

### ISSUE THREAD

**Issue by akavi1** [AnKing-VIP/The-KING-of-Button-Add-ons#26]
The colors do not change automatically upon night mode toggle. If I open Anki in light mode, then activate night mode on my Mac, everything in Anki changes to night mode colors except the answer buttons which stay in their light mode colors until I quit and restart Anki,.

**Comment by akavi1** [comment]
v2.1.62
I don't remember entirely, but I think this has been happening for a while now

**Comment by dr-zarathustra** [comment]
⁨2.1.66
same problem on macOS Ventura

**Comment by AnKingMed** [comment]
I think for now we'll have to just rely on restarting but can look into this in the future
