### ISSUE TITLE
Confirmation for "Again" blocked on screen 1

### ISSUE THREAD

**Issue by esseivan** [AnKing-VIP/The-KING-of-Button-Add-ons#27]
For a multi-screen setup where my 2nd screen if on the left, the "Again" x position is blocked at x=0.

This is the line 76 in confirmation.py :
`x1 = max(0, x1)`

It probably was useful in a previous version (of the code) but now has no use.

**Comment by AnKingMed** [comment]
@abdnh would you mind testing this PR? If everything is working fine that's fine to push it
