### ISSUE TITLE
issue shared on ankiweb

### ISSUE THREAD

**Issue by AnKingMed** [AnKing-VIP/The-KING-of-Button-Add-ons#33]
issue was shared 1/17 on ankiweb

> However, the recent update has caused the add on to be non-usable. 
> 
> The error message from Anki shows: 
> 
> When loading '⁨The KING of Button Add-ons⁩':
> ⁨Traceback (most recent call last):
>  line 279, in <module>
>     gui_hooks.theme_did_change.append(on_theme_did_change)
> AttributeError: module 'aqt.gui_hooks' has no attribute 'theme_did_change'
> 
> 
> I hope that you'll be able to fix this asap! and thank you so much :)

**Comment by AnKingMed** [comment]
@abdnh any idea if this was caused by your updates? Maybe on a early version of Anki?

**Comment by abdnh** [comment]
It's an error on versions before 2.1.50 caused by the recent update that made the add-on update its styles on theme change. I'll push a fix.

**Comment by AnKingMed** [comment]
thanks. Can also just create an extra branch if that's better and only update the newer branches moving forward

**Comment by abdnh** [comment]
It's a trivial fix, so no need for a separate branch for now.
