### ISSUE TITLE
Add-on break on Anki 2.1.49 💥

### ISSUE THREAD

**Issue by JulieJAP** [AnKing-VIP/The-KING-of-Button-Add-ons#35]
Hi dear Anking Team,

I have tried to install "The KING of Button Add-on" as an alternative to the "Button colors (Good, Again)" add-on I am currently using on Anki 2.1.49 and it didn't work. I was surprised because the official page of the add-on as well as the tracker on The Anking website say that it is compatible with version 2.1.49 of Anki.

My configuration :

- Anki 2.1.49
- Night mode enabled 
- Add-ons impacting the general interface of Anki : Set Font Size, Review Heatmap
- Of course I had previously disabled the "Button colors (Good, Again)" add-on

I include the error message that popped up when starting up Anki.

Hope this will help you find what's wrong. This is a nice plugin and this is a shame it is not working.

Have a great day !

![Bug The King of Button](https://github.com/user-attachments/assets/a901936f-d054-467a-9845-7bfcd803f37f)

**Comment by kpossibles** [comment]
I got the same error. I am just going to look for another button color add-on. I'm using beautify-anki add-on which is why I'm using an older version of the app

**Comment by AnKingMed** [comment]
@abdnh can you add this to the todo list whenever you have free time? Probably just a small bug. Maybe we need a version specific upload

**Comment by abdnh** [comment]
Fixed and pushed to AnkiWeb. I forgot to update a line of code back in #33

**Comment by AnKingMed** [comment]
Thanks!
