### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by fishben777** [AnKing-VIP/The-KING-of-Button-Add-ons#36]
Hello, I am just getting started with Anki and have added this add-on. I am loving it but occasionally after pressing the spacebar to reveal the answer, it will not show. I end up having to move my mouse to where the toggle masks button usually is. I am not sure if this is a common bug or something with my system. I have included my version and a visual of the bug. Any help is appreciated.
<img width="1470" alt="Screenshot 2024-09-09 at 5 54 32 PM" src="https://github.com/user-attachments/assets/f5e45d0d-7d37-4203-a514-0b40f4f52a6e">
<img width="754" alt="Screenshot 2024-09-09 at 6 03 37 PM" src="https://github.com/user-attachments/assets/1cce65aa-a47e-440e-8876-128fd491c9a7">

**Comment by AnKingMed** [comment]
I'm not sure what you mean. What part of the addon isn't showing up?

**Comment by fishben777** [comment]
After I press the spacebar to reveal the image occlusion card, the card is not shown. It remains red until I move my mouse around. The first image sent shows the scenario before I move my mouse.

**Comment by AnKingMed** [comment]
This is for the "king of buttons addon"? Does this issue resolve after toggling this addon off?

**Comment by fishben777** [comment]
Yes

**Comment by AnKingMed** [comment]
Can you try switching your video driver in the preferences and then restarting?
![image](https://github.com/user-attachments/assets/e008075d-c267-4370-84ff-b7638e5494a7)


@abdnh have you ever heard of anything like this?

**Comment by fishben777** [comment]
Yes! That seems to have solved the issue. Thank you very much!

**Comment by abdnh** [comment]
@AnKingMed  this is a very common issue in recent Anki versions, and is usually solved by switching the video driver as you suggested.
